### ISSUE TITLE
having trouble with mysql

### ISSUE THREAD

**Issue by raviada** [neckhair/rails-on-docker#5]
```
Ravis-MacBook-Pro:rails-on-docker medlio$ docker-compose run web bundle exec rake db:setup
Starting railsondocker_dbdata_1
Starting railsondocker_db_1

ERROR: for db  Cannot start service db: Cannot link to a non running container: /railsondocker_dbdata_1 AS /railsondocker_db_1/dbdata_1
ERROR: Encountered errors while bringing up the project.

Ravis-MacBook-Pro:rails-on-docker medlio$ docker-compose ps
         Name                       Command                State       Ports   
------------------------------------------------------------------------------
railsondocker_cache_1    docker-entrypoint.sh memcached   Up         11211/tcp 
railsondocker_db_1       /entrypoint.sh mysqld            Exit 128             
railsondocker_dbdata_1   /entrypoint.sh /bin/echo m ...   Exit 0               
railsondocker_redis_1    docker-entrypoint.sh redis ...   Up         6379/tcp  
```

I am using Docker.app on mac. Any ideas?

**Comment by neckhair** [comment]
@raviada I hat the same problem last time I checked, but had no time to fix yet. The problem is that dependent containers do not wait for each other in newer Docker version (or in Docker.app). So the app container tries to connect to Mysql before that one is ready.

**Comment by neckhair** [comment]
I had another look into this today and will push an update later. Basically the problem is that MySQL takes quite some time to initialize for the first time. So when you start with the app just run:

    docker-compose up -d db
    docker-compose run web bundle exec rake db:setup
    docker-compose up

This means you start MySQL manually in the background and give it some time to initialize. Then you start the DB setup. I didn't have to start the MySQL container manually when it was initialized later.
